### ISSUE TITLE
Expand README to Document Cluster Dynamics API and Build Options

### ISSUE THREAD

**Issue by SeanSiders** [G-PIES/G-PIES#17]
- Show how to use the cluster dynamics API to run a simulation (reactor and material classes, and the public functions of ClusterDynamics)
- Describe all of the current build options in Makefile
- Code Examples
- Architecture Support

**Comment by DylanSOldham** [comment]
The Code Examples might be worth revisiting once we flesh out our CLI, but for now our example frontend fills that purpose well.
