### ISSUE TITLE
Remove References to `USE_CUDA` in `ClusterDynamicsImpl`

### ISSUE THREAD

**Issue by SeanSiders** [G-PIES/G-PIES#60]
I'm pretty sure these are artifacts of the mono version of `ClusterDynamicsImpl`. Since CUDA and CPU versions are separate implementations now, we should be able to remove all CUDA compile-time checks in the `.cpp`s.

**Files**
*src/cluster_dynamics/cuda/cluster_dynamics_cuda_impl.cpp*
*src/cluster_dynamics/cuda/cluster_dynamics_impl.cpp*

**Comment by DylanSOldham** [comment]
This is being done as part of #58
