### ISSUE TITLE
Boost Program Options

### ISSUE THREAD

**Issue by olivecon** [G-PIES/G-PIES#93]
Our current method for parsing arguments just uses argc/argv which means most arguments are dependent on other arguments being used (not necessarily ideal). This task is to use a C++ library to parse the arguments in a smarter way allowing the user more customization in how they want to run the simulation.

**Comment by SeanSiders** [comment]
I'm gonna start a prototype for this in `boost` @olivecon you're welcome to contribute to the branch too!
